version: '3.7'
services:
  mongo:
    build:
      context: .
      dockerfile: docker/dockerfile.mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      net_mongo:
        ipv4_address: 172.16.100.2
  # cart:
  #   volumes: 
  #     - .:/opt/app
  #   build:
  #     context: .
  #     dockerfile: docker/dockerfile.app.prod
  #   env_file:
  #     - ./.env
  #   ports:
  #     - ${SERVER_PORT}:${SERVER_PORT}
  #   networks:
  #     net_mongo:
  #       ipv4_address: 172.16.100.4
networks:
  net_mongo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/24