version: '3.7'
services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongo-database
    ports:
      - 27017:27017
    volumes:
      - "./mongo/bk:/bk"
      - "./mongo/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      net_mongo:
        ipv4_address: 172.16.18.2

networks:
  net_mongo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.18.0/24